import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import './styles.css';

const API = (globalThis as { __API_URL?: string }).__API_URL || 'http://localhost:8000';
type Issue = { id:number; title:string; description:string; status:'open'|'closed'; priority:'low'|'medium'|'high'; version:number; updated_at:string; created_at:string };
type ListResponse = { items:Issue[]; total:number; page:number; limit:number; pages:number };

async function request<T>(path:string, options?:RequestInit):Promise<T> { const res = await fetch(`${API}${path}`, {headers:{'Content-Type':'application/json', ...(options?.headers || {})}, ...options}); if(!res.ok){ const body=await res.json().catch(()=>({})); throw new Error(body.detail || 'Request failed'); } return res.status===204 ? undefined as T : res.json(); }

function Layout({children}:{children:React.ReactNode}) { return <><header><Link to="/" className="brand">Issue Tracker</Link><nav><Link to="/">All issues</Link><Link className="button" to="/new">Create issue</Link></nav></header><main>{children}</main></>; }
function Form({existing, onSaved}:{existing?:Issue; onSaved:(issue:Issue)=>void}) { const nav=useNavigate(); const [form,setForm]=useState({title:existing?.title||'',description:existing?.description||'',status:existing?.status||'open',priority:existing?.priority||'medium'}); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault(); setError(''); if(!form.title.trim()){setError('Title is required');return;} if(form.title.length>200){setError('Title must be 200 characters or fewer');return;} if(/[<>]/.test(form.title)){setError('Title cannot contain < or > characters');return;} setSaving(true); try { const saved=await request<Issue>(existing?`/issues/${existing.id}`:'/issues',{method:existing?'PUT':'POST',body:JSON.stringify({...form, ...(existing?{version:existing.version}: {})})}); onSaved(saved); nav(`/issues/${saved.id}`); } catch(err){setError(err instanceof Error?err.message:'Failed to save issue');} finally{setSaving(false);} };
 return <form className="card form" onSubmit={submit}><h1>{existing?'Edit issue':'Create issue'}</h1>{error&&<div className="error" role="alert">{error}</div>}<label htmlFor="title">Title<span aria-hidden="true"> *</span></label><input id="title" value={form.title} maxLength={201} onChange={e=>setForm({...form,title:e.target.value})} aria-required="true"/><div className="hint">{form.title.length}/200 characters</div><label htmlFor="description">Description</label><textarea id="description" rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="row"><div><label htmlFor="status">Status</label><select id="status" value={form.status} onChange={e=>setForm({...form,status:e.target.value as Issue['status']})}><option value="open">Open</option><option value="closed">Closed</option></select></div><div><label htmlFor="priority">Priority</label><select id="priority" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Issue['priority']})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div></div><button disabled={saving}>{saving?'Saving…':existing?'Save changes':'Create issue'}</button></form>;
}
function ListPage(){const [data,setData]=useState<ListResponse>({items:[],total:0,page:1,limit:10,pages:0}); const [query,setQuery]=useState(''); const [status,setStatus]=useState(''); const [priority,setPriority]=useState(''); const [page,setPage]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState(false); useEffect(()=>{setLoading(true); const params=new URLSearchParams({page:String(page),limit:'10'}); if(query)params.set('search',query);if(status)params.set('status',status);if(priority)params.set('priority',priority); request<ListResponse>(`/issues?${params}`).then(setData).catch(()=>setError(true)).finally(()=>setLoading(false));},[query,status,priority,page]); return <section><div className="page-title"><div><p className="eyebrow">WORKSPACE</p><h1>All issues</h1></div><Link className="button" to="/new">+ New issue</Link></div><div className="filters"><label className="sr-only" htmlFor="search">Search issues</label><input id="search" placeholder="Search issues…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/><select aria-label="Filter by status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option><option value="open">Open</option><option value="closed">Closed</option></select><select aria-label="Filter by priority" value={priority} onChange={e=>{setPriority(e.target.value);setPage(1)}}><option value="">All priorities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div>{loading?<div className="state">Loading issues…</div>:error?<div className="state error" role="alert">Failed to load. Check your connection and try again.</div>:data.items.length===0?<div className="state">No issues found</div>:<><div className="issue-grid">{data.items.map(issue=><Link className="card issue" to={`/issues/${issue.id}`} key={issue.id}><div className="issue-meta"><span className={`badge ${issue.status}`}>{issue.status}</span><span className={`priority ${issue.priority}`}>{issue.priority}</span></div><h2>{issue.title}</h2><p>{issue.description||'No description'}</p><small>Updated {new Date(issue.updated_at).toLocaleDateString()}</small></Link>)}</div><div className="pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {data.page} of {Math.max(data.pages,1)}</span><button disabled={page>=data.pages} onClick={()=>setPage(page+1)}>Next</button></div></>}</section>}
function DetailPage(){const {id}=useParams(); const nav=useNavigate(); const [issue,setIssue]=useState<Issue>(); const [error,setError]=useState(''); useEffect(()=>{request<Issue>(`/issues/${id}`).then(setIssue).catch(e=>setError(e.message))},[id]); if(error)return <div className="state error">{error}</div>; if(!issue)return <div className="state">Loading issue…</div>; return <article className="card detail"><div className="issue-meta"><span className={`badge ${issue.status}`}>{issue.status}</span><span className={`priority ${issue.priority}`}>{issue.priority} priority</span></div><h1>{issue.title}</h1><p className="description">{issue.description||'No description provided.'}</p><small>Last updated {new Date(issue.updated_at).toLocaleString()}</small><div className="actions"><Link className="button" to={`/issues/${issue.id}/edit`}>Edit issue</Link><button className="danger" onClick={async()=>{if(confirm('Delete this issue?')){try{await request(`/issues/${issue.id}`,{method:'DELETE',headers:{'X-User-Role':'admin'}});nav('/')}catch(e){setError(e instanceof Error?e.message:'Delete failed')}}}}>Delete</button></div>{error&&<div className="error">{error}</div>}</article>}
function App(){return <Layout><Routes><Route path="/" element={<ListPage/>}/><Route path="/new" element={<Form onSaved={()=>{}}/>}/><Route path="/issues/:id" element={<DetailPage/>}/><Route path="/issues/:id/edit" element={<EditPage/>}/></Routes></Layout>};
function EditPage(){const {id}=useParams();const [issue,setIssue]=useState<Issue>();const [error,setError]=useState('');useEffect(()=>{request<Issue>(`/issues/${id}`).then(setIssue).catch(e=>setError(e.message))},[id]);if(error)return <div className="state error">{error}</div>;return issue?<Form existing={issue} onSaved={()=>{}}/>:<div className="state">Loading issue…</div>}

export default App;
const root = document.getElementById('root');
if (root) createRoot(root).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);
